/**
 * TenderX - Premium GST Calculator Logic
 * Handles real-time tax computation and history management
 */

document.addEventListener('DOMContentLoaded', () => {
    // DOM Elements
    const amountInput = document.getElementById('amount');
    const gstRateSelect = document.getElementById('gst-rate');
    const customRateInput = document.getElementById('custom-rate');
    const customRateContainer = document.getElementById('custom-rate-container');
    const modeInputs = document.querySelectorAll('input[name="gst-mode"]');
    
    const resBase = document.getElementById('res-base');
    const resTax = document.getElementById('res-tax');
    const resCgst = document.getElementById('res-cgst');
    const resSgst = document.getElementById('res-sgst');
    const resTotal = document.getElementById('res-total');
    
    const resetBtn = document.getElementById('reset-btn');
    const copyBtn = document.getElementById('copy-btn');
    const clearHistoryBtn = document.getElementById('clear-history');
    const historyList = document.getElementById('history-list');
    const toast = document.getElementById('toast');

    // State
    let history = JSON.parse(localStorage.getItem('tx_gst_history')) || [];

    // Initialize
    renderHistory();

    // Event Listeners
    amountInput.addEventListener('input', calculate);
    gstRateSelect.addEventListener('change', () => {
        if (gstRateSelect.value === 'custom') {
            customRateContainer.classList.remove('hidden');
        } else {
            customRateContainer.classList.add('hidden');
        }
        calculate();
    });
    customRateInput.addEventListener('input', calculate);
    modeInputs.forEach(input => input.addEventListener('change', calculate));

    resetBtn.addEventListener('click', reset);
    copyBtn.addEventListener('click', copySummary);
    clearHistoryBtn.addEventListener('click', clearHistory);

    // Core Logic
    function calculate() {
        const amount = parseFloat(amountInput.value) || 0;
        let rate = gstRateSelect.value === 'custom' 
            ? parseFloat(customRateInput.value) || 0 
            : parseFloat(gstRateSelect.value);
        
        const mode = document.querySelector('input[name="gst-mode"]:checked').value;
        
        let baseAmount, gstAmount, totalAmount;

        if (mode === 'add') {
            baseAmount = amount;
            gstAmount = (baseAmount * rate) / 100;
            totalAmount = baseAmount + gstAmount;
        } else {
            // Remove GST Formula: Total / (1 + Rate/100)
            totalAmount = amount;
            baseAmount = totalAmount / (1 + (rate / 100));
            gstAmount = totalAmount - baseAmount;
        }

        const cgst = gstAmount / 2;
        const sgst = gstAmount / 2;

        updateUI(baseAmount, gstAmount, cgst, sgst, totalAmount);
    }

    function updateUI(base, tax, cgst, sgst, total) {
        resBase.innerText = formatCurrency(base);
        resTax.innerText = formatCurrency(tax);
        resCgst.innerText = formatCurrency(cgst);
        resSgst.innerText = formatCurrency(sgst);
        resTotal.innerText = formatCurrency(total);
        
        // Dynamic labels for CGST/SGST
        const rate = gstRateSelect.value === 'custom' 
            ? parseFloat(customRateInput.value) || 0 
            : parseFloat(gstRateSelect.value);
        
        document.querySelector('#res-cgst').previousElementSibling.innerText = `CGST (${rate/2}%)`;
        document.querySelector('#res-sgst').previousElementSibling.innerText = `SGST (${rate/2}%)`;
    }

    function formatCurrency(val) {
        return new Intl.NumberFormat('en-IN', {
            style: 'currency',
            currency: 'INR',
            maximumFractionDigits: 2
        }).format(val);
    }

    function reset() {
        amountInput.value = '';
        gstRateSelect.value = '18';
        customRateInput.value = '';
        customRateContainer.classList.add('hidden');
        document.getElementById('add-gst').checked = true;
        calculate();
    }

    function copySummary() {
        const amount = amountInput.value;
        if (!amount || amount == 0) return;

        const summary = `
TenderX GST Calculation Summary
------------------------------
Type: ${document.querySelector('input[name="gst-mode"]:checked').value === 'add' ? 'Added GST' : 'Removed GST'}
Base Amount: ${resBase.innerText}
GST Amount: ${resTax.innerText}
Net Total: ${resTotal.innerText}
------------------------------
Generated by TenderX Solutions
        `.trim();

        navigator.clipboard.writeText(summary).then(() => {
            showToast('Summary copied to clipboard!');
            saveToHistory();
        });
    }

    function saveToHistory() {
        const entry = {
            id: Date.now(),
            date: new Date().toLocaleString(),
            mode: document.querySelector('input[name="gst-mode"]:checked').value,
            base: resBase.innerText,
            tax: resTax.innerText,
            total: resTotal.innerText,
            rate: gstRateSelect.value === 'custom' ? customRateInput.value : gstRateSelect.value
        };

        history.unshift(entry);
        if (history.length > 20) history.pop();
        
        localStorage.setItem('tx_gst_history', JSON.stringify(history));
        renderHistory();
    }

    function renderHistory() {
        if (history.length === 0) {
            historyList.innerHTML = `
                <div class="text-center py-xl" style="opacity: 0.5;">
                    <i class="fas fa-clock-rotate-left" style="font-size: 2rem; margin-bottom: 10px;"></i>
                    <p style="font-size: 0.85rem;">No history found</p>
                </div>
            `;
            return;
        }

        historyList.innerHTML = history.map(item => `
            <div class="tx-gst-history-item animate-fade">
                <div class="tx-gst-history-info">
                    <h4>${item.total}</h4>
                    <p>${item.date} • ${item.rate}% ${item.mode.toUpperCase()}</p>
                </div>
                <div class="tx-gst-history-amount" style="font-size: 0.8rem; opacity: 0.7;">
                    ${item.base}
                </div>
            </div>
        `).join('');
    }

    function clearHistory() {
        if (confirm('Clear all calculation history?')) {
            history = [];
            localStorage.removeItem('tx_gst_history');
            renderHistory();
        }
    }

    function showToast(msg) {
        document.getElementById('toast-msg').innerText = msg;
        toast.classList.add('active');
        setTimeout(() => toast.classList.remove('active'), 3000);
    }
});
